name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run example
        run: |
          python3 example.py

  typing:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r requirements-aws.txt
          pip install mypy

      - name: mypy
        run: |
          mypy .
